import type { Language } from "./types";

/**
 * Bilingual UI strings (English + Chinese) and date formatting helpers.
 * Newspaper content is generated by the AI; these are only chrome/labels.
 */

export type TranslationKey =
  | "appTitle"
  | "appSubtitle"
  | "leadHeadline"
  | "leadSubhead"
  | "cta"
  | "createAnother"
  | "home"
  | "copyLink"
  | "copied"
  | "download"
  | "scanToCreate"
  | "scanToView"
  | "name"
  | "namePlaceholder"
  | "team"
  | "teamPlaceholder"
  | "achievement"
  | "achievementPlaceholder"
  | "futureDate"
  | "photo"
  | "takePhoto"
  | "choosePhoto"
  | "surpriseMe"
  | "generate"
  | "generating"
  | "generatingArticle"
  | "generatingImage"
  | "language"
  | "category"
  | "myNewspapers"
  | "noSaved"
  | "delete"
  | "close"
  | "vol"
  | "edition"
  | "price"
  | "byline"
  | "pullQuote"
  | "reward"
  | "published"
  | "noIllustration"
  | "requiredFields"
  | "photoRequired"
  | "dateRequired"
  | "shareLink"
  | "newspaperOf"
  | "theFuture"
  | "landingBody"
  | "location"
  | "locationPlaceholder"
  | "memory"
  | "memoryPlaceholder"
  | "viewNewspaper"
  | "viewCard"
  | "noImage";

const en: Record<TranslationKey, string> = {
  appTitle: "THE FUTURE TIME CAPSULE",
  appSubtitle: "Dispatches From a Tomorrow That Hasn't Happened Yet",
  leadHeadline: "WHO WILL YOU BE IN THE FUTURE?",
  leadSubhead:
    "Write your name, plant your dream, and let the future write you a front page.",
  cta: "Create Your Front Page",
  createAnother: "Create Another",
  home: "Home",
  copyLink: "Copy Link",
  copied: "Copied!",
  download: "Download",
  scanToCreate: "Scan to create your own",
  scanToView: "Scan to view this newspaper",
  name: "Your Name",
  namePlaceholder: "e.g. Alex Chen",
  team: "Your Team",
  teamPlaceholder: "e.g. Trae Friends",
  achievement: "Your Future Achievement",
  achievementPlaceholder:
    "e.g. Led the first team to deploy a self-sustaining Mars colony...",
  futureDate: "Future Date",
  photo: "Your Photo",
  takePhoto: "Take Photo",
  choosePhoto: "Choose Photo",
  surpriseMe: "Surprise Me",
  generate: "Generate Newspaper",
  generating: "Generating...",
  generatingArticle: "Writing your future story...",
  generatingImage: "Illustrating the scene...",
  language: "Language",
  category: "Category",
  myNewspapers: "My Newspapers",
  noSaved: "No saved newspapers yet.",
  delete: "Delete",
  close: "Close",
  vol: "VOL.",
  edition: "EDITION",
  price: "PRICE 1 FUTURE-COIN",
  byline: "By Our Future Correspondent",
  pullQuote: "QUOTE",
  reward: "REWARD",
  published: "Published",
  noIllustration: "",
  requiredFields: "Please fill in your name, team, and achievement.",
  photoRequired: "Please add your photo.",
  dateRequired: "Please choose a future date.",
  shareLink: "Share Link",
  newspaperOf: "Future Newspaper of",
  theFuture: "The Future",
  landingBody:
    "Type your name. Pick a future date. Tell us the achievement you haven't achieved yet. Our AI journalist will write you a full front-page newspaper from that future year — complete with a sepia-toned photo, a pull quote, and a lavish reward. Then share it with a QR code.",
  location: "Your Location",
  locationPlaceholder: "e.g. Zhengzhou, China",
  memory: "A Special Memory",
  memoryPlaceholder: "e.g. That moment we laughed together...",
  viewNewspaper: "Newspaper View",
  viewCard: "Card View",
  noImage: "No Image",
};

const zh: Record<TranslationKey, string> = {
  appTitle: "未来时光胶囊",
  appSubtitle: "来自尚未发生的明天的电讯",
  leadHeadline: "未来你会成为谁？",
  leadSubhead: "写下你的名字，种下你的梦想，让未来为你写一篇头版。",
  cta: "生成你的头版",
  createAnother: "再做一个",
  home: "首页",
  copyLink: "复制链接",
  copied: "已复制！",
  download: "下载",
  scanToCreate: "扫码创建你自己的",
  scanToView: "扫码查看这份报纸",
  name: "你的名字",
  namePlaceholder: "例如：陈小明",
  team: "你的团队",
  teamPlaceholder: "例如：Trae Friends",
  achievement: "你的未来成就",
  achievementPlaceholder: "例如：带领第一支团队建立自给自足的火星殖民地……",
  futureDate: "未来日期",
  photo: "你的照片",
  takePhoto: "拍照",
  choosePhoto: "从相册选择",
  surpriseMe: "给我惊喜",
  generate: "生成报纸",
  generating: "生成中……",
  generatingArticle: "正在书写你的未来故事……",
  generatingImage: "正在绘制场景……",
  language: "语言",
  category: "分类",
  myNewspapers: "我的报纸",
  noSaved: "还没有保存的报纸。",
  delete: "删除",
  close: "关闭",
  vol: "第",
  edition: "期",
  price: "售价 1 未来币",
  byline: "本报记者发自未来",
  pullQuote: "语录",
  reward: "奖赏",
  published: "出版于",
  noIllustration: "",
  requiredFields: "请填写姓名、团队和成就。",
  photoRequired: "请上传你的照片。",
  dateRequired: "请选择一个未来日期。",
  shareLink: "分享链接",
  newspaperOf: "未来报纸：",
  theFuture: "未来",
  landingBody:
    "输入你的名字，选择一个未来日期，写下你尚未实现的成就。我们的AI记者将为你撰写一篇来自那个未来年份的头版报纸——配有复古照片、名言警句和丰厚奖赏。然后用二维码分享它。",
  location: "你的位置",
  locationPlaceholder: "例如：郑州，中国",
  memory: "一段特别的记忆",
  memoryPlaceholder: "例如：我们一起欢笑的那个时刻……",
  viewNewspaper: "报纸视图",
  viewCard: "卡片视图",
  noImage: "无图片",
};

const dicts: Record<Language, Record<TranslationKey, string>> = { en, zh };

export function t(lang: Language, key: TranslationKey): string {
  return dicts[lang][key] ?? key;
}

/** Format an ISO date string in the given language, e.g. "July 4, 2035" / "2035年7月4日". */
export function formatDate(iso: string, lang: Language): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return iso;
  if (lang === "zh") {
    return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日`;
  }
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/** Year-based era bucket for accent color shifting. */
export function yearEra(year: number): "near" | "mid" | "far" {
  if (year <= 2030) return "near";
  if (year <= 2040) return "mid";
  return "far";
}

export const CATEGORIES: { id: string; en: string; zh: string }[] = [
  { id: "tech", en: "Tech & Coding", zh: "科技与编程" },
  { id: "ai", en: "AI Mayhem", zh: "AI疯狂" },
  { id: "money", en: "Money & Startups", zh: "金钱与创业" },
  { id: "time", en: "Time & Chaos", zh: "时间与混乱" },
  { id: "all", en: "General", zh: "综合" },
];

export function categoryName(id: string, lang: Language): string {
  const c = CATEGORIES.find((c) => c.id === id);
  return c ? c[lang] : id;
}
